### ISSUE TITLE
borderWidth, Android下设为0.5不显示边框，IOS下设为0.5正常工作！

### ISSUE THREAD

**Issue by diggali** [apicloudcom/UIListView#2]
看到源码里：
Android: public int borderWidth = 1;
IOS: borderWidth:[_styles floatValueForKey:@"borderWidth" defaultValue:1.0]

是不是Android下变量数据类型为int的原因，可否升级成float类型，1边框不好看，现在主流都是设成0.5边框。感谢。

**Comment by diggali** [comment]
1、设置loadingImg后，【加载中】的状态时，图标还是默认的，没有被替换成自定义的。
2、设置rightBtns后，IOS下，向右滑动cell会有弹动效果，导致不能右滑关闭窗口。不设置rightBtns，可以右滑关闭窗口。

**Comment by sunzhengcuan** [comment]
新版本已修复此问题。如果还存在问题请移步APICloud官方论坛发帖提问，会有想过技术提供支持。
